/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import web.funciones;

/**
 *
 * @author Diabulus
 */
public class Login extends javax.swing.JFrame {
private static String privilegios;
private static String usuario;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnloginaceptar = new javax.swing.JButton();
        txtloginusuario = new javax.swing.JTextField();
        txtloginpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnloginaceptar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Al Sistema");

        btnloginaceptar.setText("Aceptar");
        btnloginaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginaceptarActionPerformed(evt);
            }
        });

        txtloginusuario.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtloginusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginusuarioActionPerformed(evt);
            }
        });
        txtloginusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtloginusuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtloginusuarioKeyReleased(evt);
            }
        });

        txtloginpass.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtloginpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtloginpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtloginpassKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setText("Pass:");

        btnloginaceptar1.setText("Cancelar");
        btnloginaceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginaceptar1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresarSistema.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtloginusuario)
                            .addComponent(txtloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnloginaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnloginaceptar1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtloginusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnloginaceptar1)
                    .addComponent(btnloginaceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginaceptarActionPerformed
        entrar();
    }//GEN-LAST:event_btnloginaceptarActionPerformed

    public String valorusuario(){
        return privilegios;
    }
    
    public String usuario(){
        return usuario;
    }
    
    private void txtloginusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginusuarioActionPerformed

    private void txtloginpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginpassKeyReleased

    }//GEN-LAST:event_txtloginpassKeyReleased

    private void txtloginusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginusuarioKeyReleased

    }//GEN-LAST:event_txtloginusuarioKeyReleased

    private void btnloginaceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginaceptar1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnloginaceptar1ActionPerformed

    private void txtloginusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginusuarioKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
           entrar();
        }
    }//GEN-LAST:event_txtloginusuarioKeyPressed

    private void txtloginpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginpassKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
           entrar();
        }
    }//GEN-LAST:event_txtloginpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void entrar(){
        String user = txtloginusuario.getText().toLowerCase();
        String pass = txtloginpass.getText().toLowerCase();
        int largologin=txtloginusuario.getText().length();
        int largopass=txtloginpass.getText().length();
        //JOptionPane.showMessageDialog(null, "USUARIO: "+user+" LARGO: "+largologin+"\nPASS: "+pass+" LARGO: "+largopass);        
        if( txtloginpass.getText().length() == 0 || txtloginusuario.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Usuario y/o Pass Vacios", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                if(new funciones().compararlogin(user,pass)==true){
                    System.out.println("SI ENTRA");
                    Menu m = new ventanas.Menu();
                    m.setLocationRelativeTo(null);
                    m.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Usuario y/o Pass Incorrecto", "Error",JOptionPane.ERROR_MESSAGE);
                    txtloginpass.setText("");
                    txtloginusuario.setText("");
                    txtloginusuario.requestFocus();
                }
                //privilegios = new funciones().obtenerPrivilegio(user, pass);
                //JOptionPane.showMessageDialog(null, "PRIVILEGIOS: "+privilegios);
//                if(new funciones().compararlogin(loginusuario,loginpass)==true){
//                            this.dispose();
//                            usuario = loginusuario;
//                            //new Menumantenimiento().setVisible(true);
//                }else{
//                   JOptionPane.showMessageDialog(null,"Usuario y/o Pass Incorrecto", "Error",JOptionPane.ERROR_MESSAGE);
//                    txtloginpass.setText("");
//                    txtloginusuario.setText("");
//                    txtloginusuario.requestFocus();
//                }
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginaceptar;
    private javax.swing.JButton btnloginaceptar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtloginpass;
    private javax.swing.JTextField txtloginusuario;
    // End of variables declaration//GEN-END:variables
}
