/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Diabulus
 */
public class Login extends javax.swing.JFrame {
private static String privilegios;
private static String usuario;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnloginaceptar = new javax.swing.JButton();
        txtloginusuario = new javax.swing.JTextField();
        txtloginpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Al Sistema");

        btnloginaceptar.setText("Aceptar");
        btnloginaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginaceptarActionPerformed(evt);
            }
        });

        txtloginusuario.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtloginusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginusuarioActionPerformed(evt);
            }
        });
        txtloginusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtloginusuarioKeyReleased(evt);
            }
        });

        txtloginpass.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtloginpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtloginpassKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setText("Pass:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ingresar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtloginusuario)
                            .addComponent(txtloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnloginaceptar)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtloginusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnloginaceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginaceptarActionPerformed
    entrar();
    }//GEN-LAST:event_btnloginaceptarActionPerformed

    public String valorusuario(){
    return privilegios;
    }
    
    public String usuario(){
        return usuario;
    }
    
    private void txtloginusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginusuarioActionPerformed

    private void txtloginpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginpassKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
           entrar();
        }
    }//GEN-LAST:event_txtloginpassKeyReleased

    private void txtloginusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginusuarioKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
           entrar();
        }
    }//GEN-LAST:event_txtloginusuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void entrar(){
//        JOptionPane.showMessageDialog(null, "ASDF");
//        int largologin=txtloginusuario.getText().length();
//        int largopass=txtloginpass.getText().length();
//        JOptionPane.showMessageDialog(null, "User: "+largologin+"\nPass: "+largopass);
//        if( txtloginpass.getText().length() == 0 || txtloginusuario.getText().length() == 0){
//                JOptionPane.showMessageDialog(null, "Usuario y/o Pass Vacios", "Error", JOptionPane.ERROR_MESSAGE);
//            }else{
//                String loginusuario = txtloginusuario.getText();
//                String loginpass = txtloginpass.getText();
//                // int loginusuario = Integer.parseInt(txtloginusuario.getText());
//                //int loginpass = Integer.parseInt(txtloginpass.getText());
//                 privilegios = new funcioneslogin().buscarnombre(loginusuario, loginpass);
//                if(new funcioneslogin().compararlogin(loginusuario,loginpass)==true){
//                            this.dispose();
//                            usuario= loginusuario;
//                            new Menumantenimiento().setVisible(true);
//                }else{
//                   JOptionPane.showMessageDialog(null,"Usuario y/o Pass Incorrecto", "Error",JOptionPane.ERROR_MESSAGE);
//                    txtloginpass.setText("");
//                    txtloginusuario.setText("");
//                    txtloginusuario.requestFocus();
//                }
//            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginaceptar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtloginpass;
    private javax.swing.JTextField txtloginusuario;
    // End of variables declaration//GEN-END:variables
}
